name: anchorescan
on:
  push:
    branches:
      - main
  pull_request:
env:
  IMAGE: 'docker.io/andsus/providersearchdataservice-v2:latest'
jobs:
  build:
    name: anchorescanjob
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        

      - name: Anchore Container Scan
        uses: anchore/scan-action@v3.1.0
        id: scanimage
        with:
          image: 'docker.io/andsus/providersearchdataservice-v2:latest'
          severity-cutoff: critical
          fail-build: false
          debug: true
          acs-report-enable: true

          
      - if: always()
        name: Upload  scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: ${{ steps.scanimage.outputs.sarif }}
 

