name: CI
on:
  push:
    branches:
      - main

        #env:
        #user_type: "rookie"
        #user_experience: "2 weeks"

  # workflow_dispatch:
  #   inputs:
  #     name:
  #       description: 'username'
  #       required: true
  #       default: 'andsus'

jobs:
  build:
    name: CI jobs
    #runs-on: p50wsl
    runs-on : self-hosted
    #runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    env:
      user_name: "rookie"
      user_experience: "2 weeks"

    steps:

      - name: Get the sources
        uses: actions/checkout@v2      
      
      - name: Run multiple-line
        run: |
          echo ${{ secrets.AZURE_SECRET_USER }}
          echo User type $user_name! You have $user_experience experience.

      - name: Run docker version
        run: |
          podman version
