name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build and Test
    #runs-on: self-hosted
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - name: Get the sources
        uses: actions/checkout@v2
      - name: Run multiple-line
        run: |
          echo add other actions to build
          echo yet another
