name: CI
on:
  push:
    branches:
      - main

        #env:
        #user_type: "rookie"
        #user_experience: "2 weeks"

  # workflow_dispatch:
  #   inputs:
  #     name:
  #       description: 'username'
  #       required: true
  #       default: 'andsus'

jobs:
  build:
    name: CI jobs
    #runs-on: p50wsl
    runs-on : self-hosted
    #runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    env:
      user_name: "rookie"
      user_experience: "2 weeks"

    steps:

      - name: Get the sources
        uses: actions/checkout@v2      
      
      - name: Run multiple-line
        run: |
          echo ${{ secrets.AZURE_SECRET_USER }}
          echo User type $user_name! You have $user_experience experience.

      - name: create container
        run: podman build . --file Dockerfile -t whs:bwapp
        
      - name: start bwapp 
        run: |
          podman run -d -p 3005:80 whs:bwapp
          wget --quiet --wait=3 http://localhost:3005/install.php?install=yes

      # - name: run security test        
      #   env:
      #     LICENSE_KEY: ${{ secrets.LICENSE_KEY }}
      #   run: |
      #     #wget https://github.com/whitehatsec-innovations/distribution/releases/latest/download/IDDast.deb          
      #     #sudo apt-get install -f ./IDDast.deb 
      #     #sudo dast-attacker-cli -accept-eula=Yes -license-key=${{ secrets.LICENSE_KEY }} -output-json=results.json -output-html=results.html .scan/*.har
      #     dast-attacker-cli -accept-eula=Yes -license-key=${{ secrets.LICENSE_KEY }} -output-json=results.json -output-html=results.html .scan/*.har

      - name: stop bwapp 
        run: |
          podman stop $(podman ps -q --filter ancestor=whs:bwapp)

      # - name: remove bwapp 
      #   run: |
      #     podman stop $(podman ps -q --filter ancestor=whs:bwapp)
