name: sonarscan1
on:
  # Trigger analysis when pushing in master or pull requests, and when creating
  # a pull request. 
  push:
    branches:
      - main
  pull_request:
      types: [opened, synchronize, reopened]


jobs:
  sonarqube:
    runs-on: p50wsl
    steps:
    - uses: actions/checkout@v2
      with:
        # Disabling shallow clone is recommended for improving relevancy of reporting
        fetch-depth: 0
    - name: set env variable
      run: |
        echo "STD_OUTPUT=$(ls -l | head -1 | awk '{print $1 "-" $2 }')" >> $GITHUB_ENV"
    - name: echo env var
      run: echo ${{ env.STD_OUTPUT }}
          
    - name: cd to project
      run: cd /home/andre/workspace/accountmanagementservice
    - name: SonarQube Scan
      uses: sonarsource/sonarqube-scan-action@master
      with:
        projectBaseDir: ./
        args: >
          -Dsonar.projectKey=AIP-Test1
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        # SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        SONAR_HOST_URL: http://10.46.137.224.0:9000
        # docker inspect -f '{{range.NetworkSettings.Networks}}{{.IPAddress}}{{end}}' sonarqube
