name: Test All
on:
  push:
    branches:
      - main
jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
    steps:
      - name: Get the sources
        uses: actions/checkout@v2
      - name: Create a release draft for a version tag
        id: create-release-draft
        uses: ./
        with:
          milliseconds: 1000
      - name: Print URL of the release draft
        run: |
            if [ "$RUNNER_OS" == "Linux" ]; then
              echo ${{ steps.create-release-draft.outputs.release-url }}
            elif [ "$RUNNER_OS" == "Windows" ]; then
              Write-Host ${{ steps.create-release-draft.outputs.release-url }}
            fi
        