name: trivyscan
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  build:
    name: trivyscanjob
    runs-on: p50wsl
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'image'
          image-ref: 'docker.io/andsus/providersearchdataservice-v2:latest'
          format: 'template'
          template: '@/contrib/sarif.tpl'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL,HIGH'
          exit-code: 0
        env:
          TRIVY_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          TRIVY_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      - if: always()
        name: Upload Trivy scan results to GitHub Security tab
        uses: actions/upload-artifact@v2
        with:
          name: trivy-results
          path: 'trivy-results.sarif'
